# Pandas_Basics

In [2]:
import pandas as pd

## 1-Creating data

there are two methods to creating data :
DataFrame AND Series

In [3]:
#Creating data By using : DataFrame
pd.DataFrame({'yes':[10,15,20],'No':[2,8,3]})

   yes  No
0   10   2
1   15   8
2   20   3

In [4]:
#Creating data By using : DataFrame
pd.DataFrame({'Name':['Sara' , 'Salah','Ahmed'],'Age':[22,21,23]})

    Name  Age
0   Sara   22
1  Salah   21
2  Ahmed   23

In [5]:
#Creating data By using : DataFrame
pd.DataFrame({'Nmae':['Sara' ,'Salah','Ahmed'] ,'Birth_Date':['15/4' ,'13/8','']},index=['First_Name','Second_name','Third_Name'])

              Nmae Birth_Date
First_Name    Sara       15/4
Second_name  Salah       13/8
Third_Name   Ahmed

In [6]:
#Creating data By using : Series
pd.Series(['Name','Age','DateOfBirth','Adress'])

0           Name
1            Age
2    DateOfBirth
3         Adress
dtype: object

In [7]:
#Creating data By using : Series
pd.Series([100,22,33,44],index=['One','Two','Three','Four'],name='Exercise')

One      100
Two       22
Three     33
Four      44
Name: Exercise, dtype: int64

## 2-Reading Data File

In [8]:
# pd.read_csv()
import pandas as pd
data = pd.read_csv("Student_Behaviour.csv")
data

,"Have you completed any certification courses, or are you currently enrolled in any?",Gender,Department,Height(CM),Weight(KG),10th Mark,12th Mark,college mark,hobbies,daily studing time,prefer to study in,salary expectation,Do you like your degree?,possibility of choosing their career based on their degree :,social medai & video games spending Time,Travelling Time,Stress Level,Financial Status,Are you doing a part-time job right now?
0,No,Male,BCA,100.0,58.0,79.0,65.0,80.0,Video Games,0 - 30 minute,Morning,40000,No,50%,1.30 - 2 hour,30 - 60 minutes,Bad,Bad,No
1,No,Female,BCA,90.0,40.0,70.0,80.0,70.0,Cinema,30 - 60 minute,Morning,15000,Yes,75%,1 - 1.30 hour,0 - 30 minutes,Bad,Bad,No
2,Yes,Male,BCA,159.0,78.0,69.5,61.0,55.0,Cinema,1 - 2 Hour,Anytime,13000,Yes,50%,More than 2 hour,30 - 60 minutes,Awful,Bad,No
3,Yes,Female,BCA,147.0,20.0,70.0,59.0,58.0,Reading books,1 - 2 Hour,Anytime,1500000,No,50%,1.30 - 2 hour,0 - 30 minutes,Bad,good,No
4,No,Male,BCA,170.0,54.0,40.0,65.0,30.0,Video Games,30 - 60 minute,Morning,50000,Yes,25%,1.30 - 2 hour,30 - 60 minutes,Good,good,No
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
230,Yes,Male,B.com ISM,170.0,76.0,72.0,67.0,65.0,Video Games,30 - 60 minute,Morning,7000,Yes,50%,More than 2 hour,30 - 60 minutes,Bad,Bad,No
231,Yes,Male,B.com ISM,172.0,52.0,72.0,70.0,76.0,Cinema,2 - 3 hour,Anytime,25000,Yes,75%,30 - 60 Minute,30 - 60 minutes,Good,good,No
232,Yes,Female,BCA,139.0,33.0,90.0,75.0,70.0,Cinema,30 - 60 minute,Night,20000,Yes,50%,30 - 60 Minute,2.30 - 3 hour,Bad,good,No
233,Yes,Female,Commerce,153.0,58.0,85.0,74.0,75.0,Cinema,0 - 30 minute,Anytime,20000,Yes,75%,More than 2 hour,2.30 - 3 hour,Awful,good,No
234,No,Female,B.com ISM,155.0,39.0,45.0,45.0,50.0,Sports,3 - 4 hour,Night,10,No,75%,30 - 60 Minute,2.30 - 3 hour,fabulous,good,No

### - Understanding Data

In [9]:
data.head() #First 5 rows

,"Have you completed any certification courses, or are you currently enrolled in any?",Gender,Department,Height(CM),Weight(KG),10th Mark,12th Mark,college mark,hobbies,daily studing time,prefer to study in,salary expectation,Do you like your degree?,possibility of choosing their career based on their degree :,social medai & video games spending Time,Travelling Time,Stress Level,Financial Status,Are you doing a part-time job right now?
0,No,Male,BCA,100.0,58.0,79.0,65.0,80.0,Video Games,0 - 30 minute,Morning,40000,No,50%,1.30 - 2 hour,30 - 60 minutes,Bad,Bad,No
1,No,Female,BCA,90.0,40.0,70.0,80.0,70.0,Cinema,30 - 60 minute,Morning,15000,Yes,75%,1 - 1.30 hour,0 - 30 minutes,Bad,Bad,No
2,Yes,Male,BCA,159.0,78.0,69.5,61.0,55.0,Cinema,1 - 2 Hour,Anytime,13000,Yes,50%,More than 2 hour,30 - 60 minutes,Awful,Bad,No
3,Yes,Female,BCA,147.0,20.0,70.0,59.0,58.0,Reading books,1 - 2 Hour,Anytime,1500000,No,50%,1.30 - 2 hour,0 - 30 minutes,Bad,good,No
4,No,Male,BCA,170.0,54.0,40.0,65.0,30.0,Video Games,30 - 60 minute,Morning,50000,Yes,25%,1.30 - 2 hour,30 - 60 minutes,Good,good,No

In [10]:
data.shape #(reows,columns)

(235, 19)

In [11]:
data.info() #the type of each columns

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 235 entries, 0 to 234
Data columns (total 19 columns):
 #   Column                                                                               Non-Null Count  Dtype
---  ------                                                                               --------------  -----
 0   Have you completed any certification courses, or are you currently enrolled in any?  235 non-null    object
 1   Gender                                                                               235 non-null    object
 2   Department                                                                           235 non-null    object
 3   Height(CM)                                                                           235 non-null    float64
 4   Weight(KG)                                                                           235 non-null    float64
 5   10th Mark                                                                            235 non-null    float64
 6   12th Mark                                                                            235 non-null    float64
 7   college mark                                                                         235 non-null    float64
 8   hobbies                                                                              235 non-null    object
 9   daily studing time                                                                   235 non-null    object
 10  prefer to study in                                                                   235 non-null    object
 11  salary expectation                                                                   235 non-null    int64
 12  Do you like your degree?                                                             235 non-null    object
 13  possibility of choosing  their career based on their degree :                        235 non-null    object
 14  social medai & video games spending Time                                             235 non-null    object
 15  Travelling Time                                                                      235 non-null    object
 16  Stress Level                                                                         235 non-null    object
 17  Financial Status                                                                     235 non-null    object
 18  Are you doing a part-time job right now?                                             235 non-null    object
dtypes: float64(5), int64(1), object(13)
memory usage: 35.0+ KB

In [12]:
data.columns.values #columns_name

array(['Have you completed any certification courses, or are you currently enrolled in any?',
       'Gender', 'Department', 'Height(CM)', 'Weight(KG)', '10th Mark',
       '12th Mark', 'college mark', 'hobbies', 'daily studing time',
       'prefer to study in', 'salary expectation',
       'Do you like your degree?',
       'possibility of choosing  their career based on their degree : ',
       'social medai & video games spending Time', 'Travelling Time ',
       'Stress Level ', 'Financial Status',
       'Are you doing a part-time job right now?'], dtype=object)

In [13]:
data.hobbies

0        Video Games
1             Cinema
2             Cinema
3      Reading books
4        Video Games
           ...
230      Video Games
231           Cinema
232           Cinema
233           Cinema
234           Sports
Name: hobbies, Length: 235, dtype: object

### Difference between loc & and iloc
The main difference between pandas loc[] vs iloc[] is loc gets DataFrame rows & columns by labels/names and iloc[] gets by integer Index/position

In [14]:
data.loc[[0,1,2,3]] #show wanted rows

,"Have you completed any certification courses, or are you currently enrolled in any?",Gender,Department,Height(CM),Weight(KG),10th Mark,12th Mark,college mark,hobbies,daily studing time,prefer to study in,salary expectation,Do you like your degree?,possibility of choosing their career based on their degree :,social medai & video games spending Time,Travelling Time,Stress Level,Financial Status,Are you doing a part-time job right now?
0,No,Male,BCA,100.0,58.0,79.0,65.0,80.0,Video Games,0 - 30 minute,Morning,40000,No,50%,1.30 - 2 hour,30 - 60 minutes,Bad,Bad,No
1,No,Female,BCA,90.0,40.0,70.0,80.0,70.0,Cinema,30 - 60 minute,Morning,15000,Yes,75%,1 - 1.30 hour,0 - 30 minutes,Bad,Bad,No
2,Yes,Male,BCA,159.0,78.0,69.5,61.0,55.0,Cinema,1 - 2 Hour,Anytime,13000,Yes,50%,More than 2 hour,30 - 60 minutes,Awful,Bad,No
3,Yes,Female,BCA,147.0,20.0,70.0,59.0,58.0,Reading books,1 - 2 Hour,Anytime,1500000,No,50%,1.30 - 2 hour,0 - 30 minutes,Bad,good,No

In [15]:
data.loc[0]

Have you completed any certification courses, or are you currently enrolled in any?                 No
Gender                                                                                            Male
Department                                                                                         BCA
Height(CM)                                                                                       100.0
Weight(KG)                                                                                        58.0
10th Mark                                                                                         79.0
12th Mark                                                                                         65.0
college mark                                                                                      80.0
hobbies                                                                                    Video Games
daily studing time                                                                       0 - 30 minute
prefer to study in                                                                             Morning
salary expectation                                                                               40000
Do you like your degree?                                                                            No
possibility of choosing  their career based on their degree :                                      50%
social medai & video games spending Time                                                 1.30 - 2 hour
Travelling Time                                                                        30 - 60 minutes
Stress Level                                                                                       Bad
Financial Status                                                                                   Bad
Are you doing a part-time job right now?                                                            No
Name: 0, dtype: object

In [16]:
data.loc[[0,1]]

,"Have you completed any certification courses, or are you currently enrolled in any?",Gender,Department,Height(CM),Weight(KG),10th Mark,12th Mark,college mark,hobbies,daily studing time,prefer to study in,salary expectation,Do you like your degree?,possibility of choosing their career based on their degree :,social medai & video games spending Time,Travelling Time,Stress Level,Financial Status,Are you doing a part-time job right now?
0,No,Male,BCA,100.0,58.0,79.0,65.0,80.0,Video Games,0 - 30 minute,Morning,40000,No,50%,1.30 - 2 hour,30 - 60 minutes,Bad,Bad,No
1,No,Female,BCA,90.0,40.0,70.0,80.0,70.0,Cinema,30 - 60 minute,Morning,15000,Yes,75%,1 - 1.30 hour,0 - 30 minutes,Bad,Bad,No

In [17]:
data.loc[0:3,'Gender']

0      Male
1    Female
2      Male
3    Female
Name: Gender, dtype: object

In [18]:
data.iloc[: , :  ] #[rows,columns]

,"Have you completed any certification courses, or are you currently enrolled in any?",Gender,Department,Height(CM),Weight(KG),10th Mark,12th Mark,college mark,hobbies,daily studing time,prefer to study in,salary expectation,Do you like your degree?,possibility of choosing their career based on their degree :,social medai & video games spending Time,Travelling Time,Stress Level,Financial Status,Are you doing a part-time job right now?
0,No,Male,BCA,100.0,58.0,79.0,65.0,80.0,Video Games,0 - 30 minute,Morning,40000,No,50%,1.30 - 2 hour,30 - 60 minutes,Bad,Bad,No
1,No,Female,BCA,90.0,40.0,70.0,80.0,70.0,Cinema,30 - 60 minute,Morning,15000,Yes,75%,1 - 1.30 hour,0 - 30 minutes,Bad,Bad,No
2,Yes,Male,BCA,159.0,78.0,69.5,61.0,55.0,Cinema,1 - 2 Hour,Anytime,13000,Yes,50%,More than 2 hour,30 - 60 minutes,Awful,Bad,No
3,Yes,Female,BCA,147.0,20.0,70.0,59.0,58.0,Reading books,1 - 2 Hour,Anytime,1500000,No,50%,1.30 - 2 hour,0 - 30 minutes,Bad,good,No
4,No,Male,BCA,170.0,54.0,40.0,65.0,30.0,Video Games,30 - 60 minute,Morning,50000,Yes,25%,1.30 - 2 hour,30 - 60 minutes,Good,good,No
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
230,Yes,Male,B.com ISM,170.0,76.0,72.0,67.0,65.0,Video Games,30 - 60 minute,Morning,7000,Yes,50%,More than 2 hour,30 - 60 minutes,Bad,Bad,No
231,Yes,Male,B.com ISM,172.0,52.0,72.0,70.0,76.0,Cinema,2 - 3 hour,Anytime,25000,Yes,75%,30 - 60 Minute,30 - 60 minutes,Good,good,No
232,Yes,Female,BCA,139.0,33.0,90.0,75.0,70.0,Cinema,30 - 60 minute,Night,20000,Yes,50%,30 - 60 Minute,2.30 - 3 hour,Bad,good,No
233,Yes,Female,Commerce,153.0,58.0,85.0,74.0,75.0,Cinema,0 - 30 minute,Anytime,20000,Yes,75%,More than 2 hour,2.30 - 3 hour,Awful,good,No
234,No,Female,B.com ISM,155.0,39.0,45.0,45.0,50.0,Sports,3 - 4 hour,Night,10,No,75%,30 - 60 Minute,2.30 - 3 hour,fabulous,good,No

In [19]:
data.iloc[:,-1] #Last coulumn

0      No
1      No
2      No
3      No
4      No
       ..
230    No
231    No
232    No
233    No
234    No
Name: Are you doing a part-time job right now?, Length: 235, dtype: object

In [20]:
data.iloc[-5:] #last five rows

,"Have you completed any certification courses, or are you currently enrolled in any?",Gender,Department,Height(CM),Weight(KG),10th Mark,12th Mark,college mark,hobbies,daily studing time,prefer to study in,salary expectation,Do you like your degree?,possibility of choosing their career based on their degree :,social medai & video games spending Time,Travelling Time,Stress Level,Financial Status,Are you doing a part-time job right now?
230,Yes,Male,B.com ISM,170.0,76.0,72.0,67.0,65.0,Video Games,30 - 60 minute,Morning,7000,Yes,50%,More than 2 hour,30 - 60 minutes,Bad,Bad,No
231,Yes,Male,B.com ISM,172.0,52.0,72.0,70.0,76.0,Cinema,2 - 3 hour,Anytime,25000,Yes,75%,30 - 60 Minute,30 - 60 minutes,Good,good,No
232,Yes,Female,BCA,139.0,33.0,90.0,75.0,70.0,Cinema,30 - 60 minute,Night,20000,Yes,50%,30 - 60 Minute,2.30 - 3 hour,Bad,good,No
233,Yes,Female,Commerce,153.0,58.0,85.0,74.0,75.0,Cinema,0 - 30 minute,Anytime,20000,Yes,75%,More than 2 hour,2.30 - 3 hour,Awful,good,No
234,No,Female,B.com ISM,155.0,39.0,45.0,45.0,50.0,Sports,3 - 4 hour,Night,10,No,75%,30 - 60 Minute,2.30 - 3 hour,fabulous,good,No

In [21]:
data.iloc[[0, 1, 2], [0,3]]

,"Have you completed any certification courses, or are you currently enrolled in any?",Height(CM)
0,No,100.0
1,No,90.0
2,Yes,159.0

In [22]:
data.loc[0:3,'Gender']

0      Male
1    Female
2      Male
3    Female
Name: Gender, dtype: object

### Indexing

In [23]:
data.set_index("Department") #make the coloumns is the index of dataset

,"Have you completed any certification courses, or are you currently enrolled in any?",Gender,Height(CM),Weight(KG),10th Mark,12th Mark,college mark,hobbies,daily studing time,prefer to study in,salary expectation,Do you like your degree?,possibility of choosing their career based on their degree :,social medai & video games spending Time,Travelling Time,Stress Level,Financial Status,Are you doing a part-time job right now?
Department,,,,,,,,,,,,,,,,,,
BCA,No,Male,100.0,58.0,79.0,65.0,80.0,Video Games,0 - 30 minute,Morning,40000,No,50%,1.30 - 2 hour,30 - 60 minutes,Bad,Bad,No
BCA,No,Female,90.0,40.0,70.0,80.0,70.0,Cinema,30 - 60 minute,Morning,15000,Yes,75%,1 - 1.30 hour,0 - 30 minutes,Bad,Bad,No
BCA,Yes,Male,159.0,78.0,69.5,61.0,55.0,Cinema,1 - 2 Hour,Anytime,13000,Yes,50%,More than 2 hour,30 - 60 minutes,Awful,Bad,No
BCA,Yes,Female,147.0,20.0,70.0,59.0,58.0,Reading books,1 - 2 Hour,Anytime,1500000,No,50%,1.30 - 2 hour,0 - 30 minutes,Bad,good,No
BCA,No,Male,170.0,54.0,40.0,65.0,30.0,Video Games,30 - 60 minute,Morning,50000,Yes,25%,1.30 - 2 hour,30 - 60 minutes,Good,good,No
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
B.com ISM,Yes,Male,170.0,76.0,72.0,67.0,65.0,Video Games,30 - 60 minute,Morning,7000,Yes,50%,More than 2 hour,30 - 60 minutes,Bad,Bad,No
B.com ISM,Yes,Male,172.0,52.0,72.0,70.0,76.0,Cinema,2 - 3 hour,Anytime,25000,Yes,75%,30 - 60 Minute,30 - 60 minutes,Good,good,No
BCA,Yes,Female,139.0,33.0,90.0,75.0,70.0,Cinema,30 - 60 minute,Night,20000,Yes,50%,30 - 60 Minute,2.30 - 3 hour,Bad,good,No
Commerce,Yes,Female,153.0,58.0,85.0,74.0,75.0,Cinema,0 - 30 minute,Anytime,20000,Yes,75%,More than 2 hour,2.30 - 3 hour,Awful,good,No
B.com ISM,No,Female,155.0,39.0,45.0,45.0,50.0,Sports,3 - 4 hour,Night,10,No,75%,30 - 60 Minute,2.30 - 3 hour,fabulous,good,No

### Filtering DataFrame

In [24]:
data[data['Gender']=='Female'] #Select the female from Gender column

,"Have you completed any certification courses, or are you currently enrolled in any?",Gender,Department,Height(CM),Weight(KG),10th Mark,12th Mark,college mark,hobbies,daily studing time,prefer to study in,salary expectation,Do you like your degree?,possibility of choosing their career based on their degree :,social medai & video games spending Time,Travelling Time,Stress Level,Financial Status,Are you doing a part-time job right now?
1,No,Female,BCA,90.0,40.0,70.0,80.0,70.0,Cinema,30 - 60 minute,Morning,15000,Yes,75%,1 - 1.30 hour,0 - 30 minutes,Bad,Bad,No
3,Yes,Female,BCA,147.0,20.0,70.0,59.0,58.0,Reading books,1 - 2 Hour,Anytime,1500000,No,50%,1.30 - 2 hour,0 - 30 minutes,Bad,good,No
5,Yes,Female,BCA,139.0,33.0,90.0,75.0,70.0,Cinema,30 - 60 minute,Night,20000,Yes,50%,30 - 60 Minute,0 - 30 minutes,Bad,good,No
11,No,Female,BCA,152.0,51.0,60.0,55.0,65.0,Cinema,2 - 3 hour,Night,20000,Yes,75%,1 - 1.30 hour,2 - 2.30 hour,Bad,Bad,No
12,Yes,Female,BCA,158.0,64.0,59.0,54.0,80.0,Reading books,30 - 60 minute,Morning,18000,Yes,75%,1 - 30 Minute,30 - 60 minutes,Bad,good,No
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
226,Yes,Female,Commerce,167.0,65.0,93.0,85.0,90.0,Reading books,1 - 2 Hour,Night,15000,Yes,75%,30 - 60 Minute,30 - 60 minutes,Good,good,No
229,No,Female,B.com ISM,153.0,60.0,60.0,70.0,70.0,Sports,1 - 2 Hour,Anytime,15000,Yes,75%,1 - 1.30 hour,0 - 30 minutes,Good,Bad,No
232,Yes,Female,BCA,139.0,33.0,90.0,75.0,70.0,Cinema,30 - 60 minute,Night,20000,Yes,50%,30 - 60 Minute,2.30 - 3 hour,Bad,good,No
233,Yes,Female,Commerce,153.0,58.0,85.0,74.0,75.0,Cinema,0 - 30 minute,Anytime,20000,Yes,75%,More than 2 hour,2.30 - 3 hour,Awful,good,No
234,No,Female,B.com ISM,155.0,39.0,45.0,45.0,50.0,Sports,3 - 4 hour,Night,10,No,75%,30 - 60 Minute,2.30 - 3 hour,fabulous,good,No

In [25]:
data.Gender=='Female'

0      False
1       True
2      False
3       True
4      False
       ...
230    False
231    False
232     True
233     True
234     True
Name: Gender, Length: 235, dtype: bool

In [26]:
data.loc[data.Gender=='Female']

,"Have you completed any certification courses, or are you currently enrolled in any?",Gender,Department,Height(CM),Weight(KG),10th Mark,12th Mark,college mark,hobbies,daily studing time,prefer to study in,salary expectation,Do you like your degree?,possibility of choosing their career based on their degree :,social medai & video games spending Time,Travelling Time,Stress Level,Financial Status,Are you doing a part-time job right now?
1,No,Female,BCA,90.0,40.0,70.0,80.0,70.0,Cinema,30 - 60 minute,Morning,15000,Yes,75%,1 - 1.30 hour,0 - 30 minutes,Bad,Bad,No
3,Yes,Female,BCA,147.0,20.0,70.0,59.0,58.0,Reading books,1 - 2 Hour,Anytime,1500000,No,50%,1.30 - 2 hour,0 - 30 minutes,Bad,good,No
5,Yes,Female,BCA,139.0,33.0,90.0,75.0,70.0,Cinema,30 - 60 minute,Night,20000,Yes,50%,30 - 60 Minute,0 - 30 minutes,Bad,good,No
11,No,Female,BCA,152.0,51.0,60.0,55.0,65.0,Cinema,2 - 3 hour,Night,20000,Yes,75%,1 - 1.30 hour,2 - 2.30 hour,Bad,Bad,No
12,Yes,Female,BCA,158.0,64.0,59.0,54.0,80.0,Reading books,30 - 60 minute,Morning,18000,Yes,75%,1 - 30 Minute,30 - 60 minutes,Bad,good,No
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
226,Yes,Female,Commerce,167.0,65.0,93.0,85.0,90.0,Reading books,1 - 2 Hour,Night,15000,Yes,75%,30 - 60 Minute,30 - 60 minutes,Good,good,No
229,No,Female,B.com ISM,153.0,60.0,60.0,70.0,70.0,Sports,1 - 2 Hour,Anytime,15000,Yes,75%,1 - 1.30 hour,0 - 30 minutes,Good,Bad,No
232,Yes,Female,BCA,139.0,33.0,90.0,75.0,70.0,Cinema,30 - 60 minute,Night,20000,Yes,50%,30 - 60 Minute,2.30 - 3 hour,Bad,good,No
233,Yes,Female,Commerce,153.0,58.0,85.0,74.0,75.0,Cinema,0 - 30 minute,Anytime,20000,Yes,75%,More than 2 hour,2.30 - 3 hour,Awful,good,No
234,No,Female,B.com ISM,155.0,39.0,45.0,45.0,50.0,Sports,3 - 4 hour,Night,10,No,75%,30 - 60 Minute,2.30 - 3 hour,fabulous,good,No

In [27]:
data.loc[(data.Gender=='Female') &(data.hobbies=='Cinema')]

,"Have you completed any certification courses, or are you currently enrolled in any?",Gender,Department,Height(CM),Weight(KG),10th Mark,12th Mark,college mark,hobbies,daily studing time,prefer to study in,salary expectation,Do you like your degree?,possibility of choosing their career based on their degree :,social medai & video games spending Time,Travelling Time,Stress Level,Financial Status,Are you doing a part-time job right now?
1,No,Female,BCA,90.0,40.0,70.0,80.0,70.0,Cinema,30 - 60 minute,Morning,15000,Yes,75%,1 - 1.30 hour,0 - 30 minutes,Bad,Bad,No
5,Yes,Female,BCA,139.0,33.0,90.0,75.0,70.0,Cinema,30 - 60 minute,Night,20000,Yes,50%,30 - 60 Minute,0 - 30 minutes,Bad,good,No
11,No,Female,BCA,152.0,51.0,60.0,55.0,65.0,Cinema,2 - 3 hour,Night,20000,Yes,75%,1 - 1.30 hour,2 - 2.30 hour,Bad,Bad,No
19,Yes,Female,BCA,109.0,42.0,60.0,70.0,88.0,Cinema,30 - 60 minute,Anytime,20000,Yes,100%,1 - 30 Minute,30 - 60 minutes,Good,good,No
22,No,Female,BCA,142.0,42.0,78.0,60.0,60.0,Cinema,1 - 2 Hour,Anytime,25000,Yes,75%,1 - 1.30 hour,1 - 1.30 hour,Bad,good,No
37,No,Female,BCA,150.0,45.0,90.0,90.0,90.0,Cinema,0 - 30 minute,Night,25000,Yes,100%,1 - 1.30 hour,0 - 30 minutes,Awful,good,No
42,No,Female,Commerce,159.0,95.0,72.0,80.0,79.0,Cinema,0 - 30 minute,Anytime,10000,Yes,50%,More than 2 hour,0 - 30 minutes,Good,good,No
60,Yes,Female,Commerce,146.0,61.0,88.0,81.0,80.0,Cinema,30 - 60 minute,Morning,15000,Yes,75%,1 - 30 Minute,30 - 60 minutes,Good,good,No
61,Yes,Female,Commerce,156.0,42.0,87.0,78.0,84.0,Cinema,30 - 60 minute,Morning,15000,Yes,75%,30 - 60 Minute,30 - 60 minutes,Good,good,No
72,No,Female,BCA,160.0,35.0,87.0,75.0,89.0,Cinema,0 - 30 minute,Anytime,10000,No,25%,1 - 30 Minute,1 - 1.30 hour,Good,Bad,No
81,Yes,Female,BCA,156.0,58.0,75.0,70.0,70.0,Cinema,More Than 4 hour,Anytime,10000,Yes,75%,More than 2 hour,30 - 60 minutes,Good,good,No
86,Yes,Female,BCA,170.0,45.0,75.0,64.0,74.0,Cinema,0 - 30 minute,Anytime,20000,No,25%,More than 2 hour,0 - 30 minutes,Good,good,No
90,Yes,Female,BCA,153.0,50.0,88.8,71.0,85.0,Cinema,3 - 4 hour,Morning,18000,Yes,100%,1 - 1.30 hour,1 - 1.30 hour,Good,good,No
96,Yes,Female,BCA,4.5,42.0,85.0,90.0,85.0,Cinema,30 - 60 minute,Anytime,20000,Yes,100%,1 - 1.30 hour,30 - 60 minutes,Good,Awful,No
111,Yes,Female,BCA,172.0,49.0,94.0,69.0,85.0,Cinema,30 - 60 minute,Anytime,12000,Yes,50%,30 - 60 Minute,2 - 2.30 hour,Bad,good,No
124,Yes,Female,BCA,154.0,45.0,72.6,62.6,85.0,Cinema,0 - 30 minute,Night,17000,Yes,100%,30 - 60 Minute,30 - 60 minutes,Good,good,No
125,Yes,Female,BCA,139.0,62.0,91.0,86.0,90.0,Cinema,30 - 60 minute,Morning,20000,Yes,75%,1 - 1.30 hour,0 - 30 minutes,Good,good,No
147,Yes,Female,B.com Accounting and Finance,148.0,78.0,71.2,79.5,70.0,Cinema,30 - 60 minute,Anytime,5000,Yes,50%,30 - 60 Minute,1 - 1.30 hour,Good,Bad,No
153,Yes,Female,BCA,155.0,43.0,79.0,61.0,70.0,Cinema,1 - 2 Hour,Night,13000,Yes,50%,1.30 - 2 hour,0 - 30 minutes,Awful,Awful,No
157,Yes,Female,BCA,155.0,50.0,80.0,73.0,80.0,Cinema,0 - 30 minute,Anytime,50000,Yes,75%,1 - 30 Minute,30 - 60 minutes,Good,Bad,Yes
166,Yes,Female,Commerce,145.0,60.0,92.0,75.0,90.0,Cinema,3 - 4 hour,Anytime,18000,Yes,100%,More than 2 hour,0 - 30 minutes,Bad,good,No
172,Yes,Female,Commerce,157.0,40.0,93.0,86.0,85.0,Cinema,30 - 60 minute,Morning,15000,Yes,50%,More than 2 hour,30 - 60 minutes,Good,Bad,No
177,Yes,Female,Commerce,154.0,62.0,70.0,50.0,60.0,Cinema,1 - 2 Hour,Night,20000,Yes,50%,1 - 1.30 hour,30 - 60 minutes,Bad,Bad,No
178,Yes,Female,Commerce,165.0,75.0,91.0,70.0,80.0,Cinema,1 - 2 Hour,Anytime,10000,Yes,50%,30 - 60 Minute,30 - 60 minutes,Bad,Awful,No
179,Yes,Female,Commerce,150.0,40.0,80.0,75.0,70.0,Cinema,1 - 2 Hour,Morning,120000,Yes,50%,1 - 1.30 hour,0 - 30 minutes,Good,Bad,No
180,Yes,Female,B.com ISM,149.0,50.0,60.0,60.0,60.0,Cinema,30 - 60 minute,Morning,15000,Yes,75%,1 - 30 Minute,30 - 60 minutes,Bad,Bad,No
194,No,Female,B.com ISM,149.0,40.0,60.0,60.0,60.0,Cinema,30 - 60 minute,Morning,15000,Yes,75%,1 - 30 Minute,30 - 60 minutes,Bad,good,No
202,Yes,Female,Commerce,160.0,68.0,96.0,92.0,80.0,Cinema,3 - 4 hour,Morning,10000,Yes,75%,1.30 - 2 hour,0 - 30 minutes,Good,good,No
206,Yes,Female,Commerce,146.0,39.0,95.6,86.0,85.0,Cinema,1 - 2 Hour,Anytime,13000,Yes,75%,30 - 60 Minute,0 - 30 minutes,Good,good,No
212,Yes,Female,Commerce,152.0,64.0,90.4,80.0,80.0,Cinema,1 - 2 Hour,Anytime,15000,Yes,75%,30 - 60 Minute,1 - 1.30 hour,Good,good,No
216,Yes,Female,Commerce,160.0,60.0,75.0,85.0,90.0,Cinema,2 - 3 hour,Anytime,20000,Yes,75%,30 - 60 Minute,30 - 60 minutes,Good,good,No
217,Yes,Female,Commerce,153.0,58.0,85.0,74.0,75.0,Cinema,0 - 30 minute,Anytime,20000,Yes,75%,More than 2 hour,0 - 30 minutes,Awful,good,No
221,Yes,Female,Commerce,153.0,45.0,83.0,73.0,75.0,Cinema,0 - 30 minute,Morning,20000,Yes,75%,30 - 60 Minute,0 - 30 minutes,Good,good,No
232,Yes,Female,BCA,139.0,33.0,90.0,75.0,70.0,Cinema,30 - 60 minute,Night,20000,Yes,50%,30 - 60 Minute,2.30 - 3 hour,Bad,good,No
233,Yes,Female,Commerce,153.0,58.0,85.0,74.0,75.0,Cinema,0 - 30 minute,Anytime,20000,Yes,75%,More than 2 hour,2.30 - 3 hour,Awful,good,No

In [28]:
data.loc[data.Department.isin(['Commerce','BCA'])] #show rows thas has im Department "['Commerce','BCA']"

,"Have you completed any certification courses, or are you currently enrolled in any?",Gender,Department,Height(CM),Weight(KG),10th Mark,12th Mark,college mark,hobbies,daily studing time,prefer to study in,salary expectation,Do you like your degree?,possibility of choosing their career based on their degree :,social medai & video games spending Time,Travelling Time,Stress Level,Financial Status,Are you doing a part-time job right now?
0,No,Male,BCA,100.0,58.0,79.0,65.0,80.0,Video Games,0 - 30 minute,Morning,40000,No,50%,1.30 - 2 hour,30 - 60 minutes,Bad,Bad,No
1,No,Female,BCA,90.0,40.0,70.0,80.0,70.0,Cinema,30 - 60 minute,Morning,15000,Yes,75%,1 - 1.30 hour,0 - 30 minutes,Bad,Bad,No
2,Yes,Male,BCA,159.0,78.0,69.5,61.0,55.0,Cinema,1 - 2 Hour,Anytime,13000,Yes,50%,More than 2 hour,30 - 60 minutes,Awful,Bad,No
3,Yes,Female,BCA,147.0,20.0,70.0,59.0,58.0,Reading books,1 - 2 Hour,Anytime,1500000,No,50%,1.30 - 2 hour,0 - 30 minutes,Bad,good,No
4,No,Male,BCA,170.0,54.0,40.0,65.0,30.0,Video Games,30 - 60 minute,Morning,50000,Yes,25%,1.30 - 2 hour,30 - 60 minutes,Good,good,No
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
224,Yes,Female,Commerce,152.0,65.0,97.0,80.0,100.0,Reading books,3 - 4 hour,Morning,15000,Yes,100%,30 - 60 Minute,0 - 30 minutes,Good,good,Yes
225,Yes,Female,Commerce,164.0,43.0,80.0,89.0,95.0,Reading books,2 - 3 hour,Morning,15000,Yes,100%,1 - 30 Minute,0 - 30 minutes,Good,good,No
226,Yes,Female,Commerce,167.0,65.0,93.0,85.0,90.0,Reading books,1 - 2 Hour,Night,15000,Yes,75%,30 - 60 Minute,30 - 60 minutes,Good,good,No
232,Yes,Female,BCA,139.0,33.0,90.0,75.0,70.0,Cinema,30 - 60 minute,Night,20000,Yes,50%,30 - 60 Minute,2.30 - 3 hour,Bad,good,No
233,Yes,Female,Commerce,153.0,58.0,85.0,74.0,75.0,Cinema,0 - 30 minute,Anytime,20000,Yes,75%,More than 2 hour,2.30 - 3 hour,Awful,good,No

### Statistics with Pandas

In [29]:
data['salary expectation'].sum()

7633195

In [30]:
data['salary expectation'].mean()

32481.68085106383

In [31]:
data[['salary expectation','Height(CM)']].max()

salary expectation    1500000.0
Height(CM)                192.0
dtype: float64

In [32]:
data.mode()

,"Have you completed any certification courses, or are you currently enrolled in any?",Gender,Department,Height(CM),Weight(KG),10th Mark,12th Mark,college mark,hobbies,daily studing time,prefer to study in,salary expectation,Do you like your degree?,possibility of choosing their career based on their degree :,social medai & video games spending Time,Travelling Time,Stress Level,Financial Status,Are you doing a part-time job right now?
0,Yes,Male,BCA,160.0,60.0,60.0,60.0,70.0,Sports,30 - 60 minute,Anytime,20000.0,Yes,75%,30 - 60 Minute,30 - 60 minutes,Good,good,No
1,NaN,NaN,NaN,NaN,NaN,75.0,70.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2,NaN,NaN,NaN,NaN,NaN,80.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN

### Grouping

In [33]:
data.groupby("Gender").sum()

,Height(CM),Weight(KG),10th Mark,12th Mark,college mark,salary expectation
Gender,,,,,,
Female,11877.5,3987.0,6239.0,5665.50,6072.80,3015035
Male,25112.0,10301.9,11818.9,10497.83,10532.43,4618160

In [34]:
data.groupby("salary expectation").sum()

                    Height(CM)  Weight(KG)  10th Mark  12th Mark  college mark
salary expectation
0                        162.0        60.0       62.0      61.30         53.00
10                       310.0        78.0       90.0      90.00        100.00
15                       152.0        32.0       80.0      60.00         70.00
17                       160.0        52.0       50.0      55.00         50.00
21                       171.0        60.0       78.0      55.00         70.00
22                       168.0        75.0       75.0      65.00         75.00
100                      160.0        50.0       85.0      80.00         60.00
500                      155.0        68.0       75.0      75.00         65.00
5000                     482.0       193.0      221.2     234.50        217.00
7000                     170.0        76.0       72.0      67.00         65.00
8000                     157.0        53.0       85.0      88.00         89.00
10000                   2615.0       932.0     1227.0    1165.00       1127.00
11000                    182.0        57.0       83.7      76.77         80.00
12000                    808.0       281.0      339.4     360.00        369.00
12500                    159.0        51.0       86.0      72.00         80.00
13000                    625.0       220.0      299.1     258.00        270.00
15000                   7614.0      2875.9     3845.3    3558.90       3463.00
16000                    325.0       117.0      151.0     127.00        130.00
17000                    668.0       235.0      277.6     239.60        270.00
18000                   1842.0       871.0      996.8     812.80        902.00
20000                   9878.5      3896.0     5117.4    4396.26       4679.96
23000                    173.0        92.0       54.0      65.00          2.00
25000                   3596.0      1414.0     1747.4    1513.30       1634.67
30000                   2081.0       856.0      939.0     844.30        863.30
35000                    353.0       133.0      181.2     145.10        165.00
40000                    790.0       321.0      388.0     356.00        373.00
45000                    150.0        48.0       60.0      77.00         50.00
50000                   1677.0       576.0      710.3     623.30        709.30
60000                    160.0        83.0       89.5      69.70         70.00
100000                   416.0       213.0      199.0     221.50        235.00
120000                   150.0        40.0       80.0      75.00         70.00
500000                   163.0        80.0       76.0      47.00         30.00
700000                   170.0        80.0       67.0      70.00         60.00
1500000                  147.0        20.0       70.0      59.00         58.00

### Sorting

In [38]:
height_sorted=data.sort_values("Height(CM)") //Sorting Columns
height_sorted

,"Have you completed any certification courses, or are you currently enrolled in any?",Gender,Department,Height(CM),Weight(KG),10th Mark,12th Mark,college mark,hobbies,daily studing time,prefer to study in,salary expectation,Do you like your degree?,possibility of choosing their career based on their degree :,social medai & video games spending Time,Travelling Time,Stress Level,Financial Status,Are you doing a part-time job right now?
96,Yes,Female,BCA,4.5,42.0,85.0,90.0,85.0,Cinema,30 - 60 minute,Anytime,20000,Yes,100%,1 - 1.30 hour,30 - 60 minutes,Good,Awful,No
1,No,Female,BCA,90.0,40.0,70.0,80.0,70.0,Cinema,30 - 60 minute,Morning,15000,Yes,75%,1 - 1.30 hour,0 - 30 minutes,Bad,Bad,No
47,No,Male,B.com Accounting and Finance,90.0,83.0,60.0,82.0,65.0,Video Games,0 - 30 minute,Anytime,100000,Yes,75%,30 - 60 Minute,1.30 - 2 hour,Awful,good,No
25,No,Male,BCA,90.0,89.0,60.0,50.0,50.0,Sports,30 - 60 minute,Morning,18000,Yes,75%,30 - 60 Minute,30 - 60 minutes,Bad,good,Yes
41,No,Female,BCA,98.0,35.0,70.0,55.0,70.0,Reading books,1 - 2 Hour,Night,20000,Yes,75%,1.30 - 2 hour,30 - 60 minutes,Good,good,No
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
73,Yes,Male,BCA,190.0,70.0,89.8,63.3,73.3,Sports,0 - 30 minute,Anytime,50000,Yes,50%,30 - 60 Minute,1 - 1.30 hour,Bad,good,No
8,No,Male,BCA,190.0,85.0,88.2,67.5,60.0,Video Games,0 - 30 minute,Morning,20000,Yes,75%,1.30 - 2 hour,1 - 1.30 hour,Bad,Bad,No
163,Yes,Male,Commerce,190.0,106.0,82.0,78.0,80.0,Reading books,1 - 2 Hour,Anytime,25000,Yes,100%,1 - 30 Minute,1.30 - 2 hour,Good,Bad,Yes
62,Yes,Male,Commerce,190.0,90.0,70.0,70.0,90.0,Cinema,More Than 4 hour,Anytime,15000,Yes,100%,More than 2 hour,30 - 60 minutes,Awful,Bad,Yes
164,No,Male,Commerce,192.0,85.0,84.0,85.0,80.0,Cinema,30 - 60 minute,Anytime,25000,Yes,100%,30 - 60 Minute,more than 3 hour,Good,Bad,No

In [43]:
sortedd=data.sort_values(["Weight(KG)"])
sortedd

,"Have you completed any certification courses, or are you currently enrolled in any?",Gender,Department,Height(CM),Weight(KG),10th Mark,12th Mark,college mark,hobbies,daily studing time,prefer to study in,salary expectation,Do you like your degree?,possibility of choosing their career based on their degree :,social medai & video games spending Time,Travelling Time,Stress Level,Financial Status,Are you doing a part-time job right now?
3,Yes,Female,BCA,147.0,20.0,70.0,59.0,58.0,Reading books,1 - 2 Hour,Anytime,1500000,No,50%,1.30 - 2 hour,0 - 30 minutes,Bad,good,No
210,Yes,Female,Commerce,152.0,32.0,80.0,60.0,70.0,Sports,1 - 2 Hour,Night,15,Yes,75%,1 - 1.30 hour,30 - 60 minutes,Bad,good,No
5,Yes,Female,BCA,139.0,33.0,90.0,75.0,70.0,Cinema,30 - 60 minute,Night,20000,Yes,50%,30 - 60 Minute,0 - 30 minutes,Bad,good,No
232,Yes,Female,BCA,139.0,33.0,90.0,75.0,70.0,Cinema,30 - 60 minute,Night,20000,Yes,50%,30 - 60 Minute,2.30 - 3 hour,Bad,good,No
41,No,Female,BCA,98.0,35.0,70.0,55.0,70.0,Reading books,1 - 2 Hour,Night,20000,Yes,75%,1.30 - 2 hour,30 - 60 minutes,Good,good,No
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
77,Yes,Male,BCA,172.0,91.0,92.0,69.0,85.0,Cinema,1 - 2 Hour,Night,15000,Yes,75%,1 - 1.30 hour,1 - 1.30 hour,Good,good,No
183,Yes,Male,B.com ISM,173.0,92.0,54.0,65.0,2.0,Cinema,0 - 30 minute,Anytime,23000,Yes,100%,More than 2 hour,1 - 1.30 hour,Good,good,No
67,Yes,Male,BCA,100.0,93.0,90.0,62.0,79.0,Reading books,30 - 60 minute,Night,18000,Yes,75%,30 - 60 Minute,30 - 60 minutes,Bad,Bad,No
42,No,Female,Commerce,159.0,95.0,72.0,80.0,79.0,Cinema,0 - 30 minute,Anytime,10000,Yes,50%,More than 2 hour,0 - 30 minutes,Good,good,No
163,Yes,Male,Commerce,190.0,106.0,82.0,78.0,80.0,Reading books,1 - 2 Hour,Anytime,25000,Yes,100%,1 - 30 Minute,1.30 - 2 hour,Good,Bad,Yes

In [49]:
data.groupby(['college mark', "Department"]).agg({'salary expectation':['sum', 'max']}) #do a function to spasfic columns

                                           salary expectation
                                                          sum    max
college mark Department
1.0          B.com Accounting and Finance               15000  15000
2.0          B.com ISM                                  23000  23000
3.0          BCA                                        15000  15000
7.5          BCA                                        15000  15000
12.0         B.com Accounting and Finance               30000  30000
...                                                       ...    ...
93.0         Commerce                                   20000  20000
95.0         B.com Accounting and Finance               50000  50000
             Commerce                                   15000  15000
97.0         Commerce                                   15000  15000
100.0        Commerce                                   30000  15000

[69 rows x 2 columns]

### Pivot Tables

In [56]:
import numpy as np
data.pivot_table(index=["salary expectation"], columns=["Department"],  aggfunc=[np.sum])

                                             sum                             \
                                       10th Mark
Department         B.com Accounting and Finance  B.com ISM     BCA Commerce
salary expectation
0                                            NaN       NaN    62.0      NaN
10                                           NaN      90.0     NaN      NaN
15                                           NaN       NaN     NaN     80.0
17                                           NaN       NaN    50.0      NaN
21                                           NaN       NaN    78.0      NaN
22                                           NaN       NaN     NaN     75.0
100                                          NaN       NaN     NaN     85.0
500                                          NaN      75.0     NaN      NaN
5000                                       161.2      60.0     NaN      NaN
7000                                         NaN      72.0     NaN      NaN
8000                                        85.0       NaN     NaN      NaN
10000                                      144.0      50.0   599.0    434.0
11000                                        NaN       NaN     NaN     83.7
12000                                        NaN      75.0   179.4     85.0
12500                                        NaN       NaN    86.0      NaN
13000                                        NaN       NaN   148.5    150.6
15000                                      143.0     330.0  1665.1   1707.2
16000                                        NaN       NaN    69.0     82.0
17000                                        NaN      55.0   222.6      NaN
18000                                        NaN       NaN   824.8    172.0
20000                                      138.0     271.0  3485.8   1222.6
23000                                        NaN      54.0     NaN      NaN
25000                                        NaN     151.0  1224.4    372.0
30000                                      155.2     169.0   614.8      NaN
35000                                        NaN       NaN    90.2     91.0
40000                                        NaN      70.0   158.0    160.0
45000                                        NaN      60.0     NaN      NaN
50000                                      152.0      50.0   508.3      NaN
60000                                        NaN       NaN    89.5      NaN
100000                                     135.0       NaN    64.0      NaN
120000                                       NaN       NaN     NaN     80.0
500000                                       NaN      76.0     NaN      NaN
700000                                       NaN      67.0     NaN      NaN
1500000                                      NaN       NaN    70.0      NaN

                                                                              \
                                       12th Mark
Department         B.com Accounting and Finance  B.com ISM      BCA Commerce
salary expectation
0                                            NaN       NaN    61.30      NaN
10                                           NaN      90.0      NaN      NaN
15                                           NaN       NaN      NaN    60.00
17                                           NaN       NaN    55.00      NaN
21                                           NaN       NaN    55.00      NaN
22                                           NaN       NaN      NaN    65.00
100                                          NaN       NaN      NaN    80.00
500                                          NaN      75.0      NaN      NaN
5000                                       164.5      70.0      NaN      NaN
7000                                         NaN      67.0      NaN      NaN
8000                                        88.0       NaN      NaN      NaN
10000                                      176.0      50.0   540.00   399.00
11000                                        NaN       NaN      NaN    76.77
12000                                        NaN      79.0   206.00    75.00
12500                                        NaN       NaN    72.00      NaN
13000                                        NaN       NaN   122.00   136.00
15000                                      152.0     327.0  1501.40  1578.50
16000                                        NaN       NaN    54.00    73.00
17000                                        NaN      57.0   182.60      NaN
18000                                        NaN       NaN   677.80   135.00
20000                                      140.0     258.0  2859.26  1139.00
23000                                        NaN      65.0      NaN      NaN
25000                                        NaN     132.0  1003.30   378.00
30000                                      145.0     159.0   540.30      NaN
35000                                        NaN       NaN    61.60    83.50
40000                                        NaN      60.0   130.00   166.00
45000                                        NaN      77.0      NaN      NaN
50000                                      133.0      50.0   440.30      NaN
60000                                        NaN       NaN    69.70      NaN
100000                                     172.0       NaN    49.50      NaN
120000                                       NaN       NaN      NaN    75.00
500000                                       NaN      47.0      NaN      NaN
700000                                       NaN      70.0      NaN      NaN
1500000                                      NaN       NaN    59.00      NaN

                                                                             \
                                      Height(CM)
Department         B.com Accounting and Finance  B.com ISM     BCA Commerce
salary expectation
0                                            NaN       NaN   162.0      NaN
10                                           NaN     310.0     NaN      NaN
15                                           NaN       NaN     NaN    152.0
17                                           NaN       NaN   160.0      NaN
21                                           NaN       NaN   171.0      NaN
22                                           NaN       NaN     NaN    168.0
100                                          NaN       NaN     NaN    160.0
500                                          NaN     155.0     NaN      NaN
5000                                       322.0     160.0     NaN      NaN
7000                                         NaN     170.0     NaN      NaN
8000                                       157.0       NaN     NaN      NaN
10000                                      314.0     170.0  1306.0    825.0
11000                                        NaN       NaN     NaN    182.0
12000                                        NaN     145.0   507.0    156.0
12500                                        NaN       NaN   159.0      NaN
13000                                        NaN       NaN   314.0    311.0
15000                                      325.0     720.0  3228.0   3341.0
16000                                        NaN       NaN   155.0    170.0
17000                                        NaN     167.0   501.0      NaN
18000                                        NaN       NaN  1530.0    312.0
20000                                      288.0     686.0  6624.5   2280.0
23000                                        NaN     173.0     NaN      NaN
25000                                        NaN     342.0  2385.0    869.0
30000                                      290.0     465.0  1326.0      NaN
35000                                        NaN       NaN   180.0    173.0
40000                                        NaN     168.0   285.0    337.0
45000                                        NaN     150.0     NaN      NaN
50000                                      305.0     170.0  1202.0      NaN
60000                                        NaN       NaN   160.0      NaN
100000                                     260.0       NaN   156.0      NaN
120000                                       NaN       NaN     NaN    150.0
500000                                       NaN     163.0     NaN      NaN
700000                                       NaN     170.0     NaN      NaN
1500000                                      NaN       NaN   147.0      NaN

                                                                             \
                                      Weight(KG)
Department         B.com Accounting and Finance  B.com ISM     BCA Commerce
salary expectation
0                                            NaN       NaN    60.0      NaN
10                                           NaN      78.0     NaN      NaN
15                                           NaN       NaN     NaN     32.0
17                                           NaN       NaN    52.0      NaN
21                                           NaN       NaN    60.0      NaN
22                                           NaN       NaN     NaN     75.0
100                                          NaN       NaN     NaN     50.0
500                                          NaN      68.0     NaN      NaN
5000                                       143.0      50.0     NaN      NaN
7000                                         NaN      76.0     NaN      NaN
8000                                        53.0       NaN     NaN      NaN
10000                                       83.0      55.0   458.0    336.0
11000                                        NaN       NaN     NaN     57.0
12000                                        NaN      50.0   186.0     45.0
12500                                        NaN       NaN    51.0      NaN
13000                                        NaN       NaN   121.0     99.0
15000                                      120.0     259.0  1221.9   1275.0
16000                                        NaN       NaN    52.0     65.0
17000                                        NaN      55.0   180.0      NaN
18000                                        NaN       NaN   749.0    122.0
20000                                      127.0     252.0  2616.0    901.0
23000                                        NaN      92.0     NaN      NaN
25000                                        NaN     117.0   912.0    385.0
30000                                      115.0     178.0   563.0      NaN
35000                                        NaN       NaN    75.0     58.0
40000                                        NaN      48.0   130.0    143.0
45000                                        NaN      48.0     NaN      NaN
50000                                      106.0      60.0   410.0      NaN
60000                                        NaN       NaN    83.0      NaN
100000                                     163.0       NaN    50.0      NaN
120000                                       NaN       NaN     NaN     40.0
500000                                       NaN      80.0     NaN      NaN
700000                                       NaN      80.0     NaN      NaN
1500000                                      NaN       NaN    20.0      NaN


                                    college mark
Department         B.com Accounting and Finance  B.com ISM      BCA Commerce
salary expectation
0                                            NaN       NaN    53.00      NaN
10                                           NaN     100.0      NaN      NaN
15                                           NaN       NaN      NaN     70.0
17                                           NaN       NaN    50.00      NaN
21                                           NaN       NaN    70.00      NaN
22                                           NaN       NaN      NaN     75.0
100                                          NaN       NaN      NaN     60.0
500                                          NaN      65.0      NaN      NaN
5000                                       152.0      65.0      NaN      NaN
7000                                         NaN      65.0      NaN      NaN
8000                                        89.0       NaN      NaN      NaN
10000                                      150.0      50.0   533.00    394.0
11000                                        NaN       NaN      NaN     80.0
12000                                        NaN      70.0   229.00     70.0
12500                                        NaN       NaN    80.00      NaN
13000                                        NaN       NaN   125.00    145.0
15000                                       76.0     325.0  1366.00   1696.0
16000                                        NaN       NaN    50.00     80.0
17000                                        NaN      60.0   210.00      NaN
18000                                        NaN       NaN   752.00    150.0
20000                                      140.0     269.0  3074.96   1196.0
23000                                        NaN       2.0      NaN      NaN
25000                                        NaN     136.0  1135.87    362.8
30000                                       87.0     213.0   563.30      NaN
35000                                        NaN       NaN    85.00     80.0
40000                                        NaN      50.0   155.00    168.0
45000                                        NaN      50.0      NaN      NaN
50000                                      175.0      50.0   484.30      NaN
60000                                        NaN       NaN    70.00      NaN
100000                                     150.0       NaN    85.00      NaN
120000                                       NaN       NaN      NaN     70.0
500000                                       NaN      30.0      NaN      NaN
700000                                       NaN      60.0      NaN      NaN
1500000                                      NaN       NaN    58.00      NaN